import Head from "next/head"
import styles from "./MainLayout.module.css"
import { Navbar } from "../Navbar"

interface Children {
  children: JSX.Element
}

export const MainLayout = ({ children }: Children) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Home - Alex Pren</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>{children}</main>
    </div>
  )
}
